posts/urls.py
from django.urls import path
from . import views


app_name = 'travel_posts'

urlpatterns = [
    path('', views.index, name='main'),
    path('follow/', views.follow_index, name='follow_index'),
    path('country/<slug:slug>/', views.country_posts, name='country_posts'),
    path(
        'profile/<str:user_name>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:user_name>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
    path('profile/<str:user_name>/', views.profile, name='profile'),
    path('create/', views.post_create, name='post_create'),
    path('post/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('post/<int:post_id>/comment/', views.add_comment, name='add_comment'),
    path('post/<int:post_id>/like/', views.post_like, name='post_like'),
    path('post/<int:post_id>/dislike/', views.post_dislike, name='post_dislike'),
    path('post/<int:post_id>/', views.post_detail, name='post_detail'),
]

travel_blog/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='travel_posts')),
]

handler404 = 'core.views.page_not_found' # noqa
handler500 = 'core.views.server_error'  # noqa
handler403 = 'core.views.permission_denied' # noqa

urlpatterns += static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)
urlpatterns += static(
    settings.STATIC_URL, document_root=settings.STATIC_ROOT
)

posts/models.py
from django.db import models
from django.contrib.auth import get_user_model
from crum import get_current_user


User = get_user_model()


class Country(models.Model):
    title = models.CharField(max_length=60)
    slug = models.SlugField(unique=True)
    description = models.TextField(null=True, blank=True)

    class Meta:
        ordering = ('title',)

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(
        verbose_name='Posts text',
        help_text="Write what's on your mind?"
    )
    pub_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Posts date and time'
    )
    author = models.ForeignKey(User,
                               null=False,
                               on_delete=models.CASCADE,
                               related_name='posts',
                               verbose_name='Author')
    country = models.ForeignKey(Country,
                                null=True,
                                blank=False,
                                on_delete=models.SET_NULL,
                                related_name='posts',
                                verbose_name='Country about which post',
                                help_text='Choose a country')
    image = models.ImageField(upload_to='posts/',
                              null=True,
                              blank=True,
                              verbose_name='Image',
                              help_text='Choose image for your post')

    def comments_count(self):
        return self.comments.count()

    def likes(self):
        return self.post_likes.all()

    def already_like(self):
        current_user = get_current_user()
        return self.post_likes.filter(user=current_user).exists()

    class Meta:
        ordering = ('-pub_date',)

    def __str__(self):
        return f'{self.pk} | {self.author} | {self.text[:15]}'


class Comments(models.Model):
    post = models.ForeignKey(Post,
                             on_delete=models.CASCADE,
                             null=False,
                             blank=False,
                             related_name='comments')
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               null=False,
                               blank=False,
                               related_name='comments')
    text = models.TextField(verbose_name='Write a comment...',
                            null=False,
                            blank=False)
    created = models.DateTimeField(auto_now_add=True,
                                   verbose_name='Comment date and time')

    def __str__(self):
        return self.text[:15]

    class Meta:
        ordering = ('-created',)


class Follow(models.Model):
    user = models.ForeignKey(User,
                             related_name='follower',
                             on_delete=models.CASCADE,
                             blank=False,
                             null=False)
    author = models.ForeignKey(User,
                               related_name='following',
                               on_delete=models.CASCADE,
                               blank=False,
                               null=False)

    def __str__(self):
        return f'Follower: {self.user}, Following: {self.author}'

    class Meta:
        unique_together = [['user', 'author']]


class Like(models.Model):
    user = models.ForeignKey(User,
                             related_name='likers',
                             on_delete=models.CASCADE,
                             blank=False,
                             null=False)
    post = models.ForeignKey(Post,
                             related_name='post_likes',
                             blank=False,
                             null=False,
                             on_delete=models.CASCADE)

    class Meta:
        unique_together = [['user', 'post']]

posts/forms.py
from django import forms
from .models import Post, Comments


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'country', 'image',)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comments
        fields = ('text',)

posts/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, HttpRequest, HttpResponseRedirect
from django.urls import reverse
from .variables import posts_per_page
from typing import Dict
from .models import Post, Country, User, Follow, Like
from .forms import PostForm, CommentForm


def index(request: HttpRequest) -> HttpResponse:
    posts = Post.objects\
        .select_related('author')\
        .select_related('country')\
        .all()

    paginator = Paginator(posts, posts_per_page)
    page_number = request.GET.get('page')
    page_posts = paginator.get_page(page_number)

    context = {
        'page_posts': page_posts,
    }
    template = 'posts/index.html'

    return render(request, template, context)


@login_required(login_url='users:login')
def follow_index(request: HttpRequest) -> HttpResponse:
    posts = Post.objects.filter(author__following__user=request.user)

    paginator = Paginator(posts, posts_per_page)
    page_number = request.GET.get('page')
    page_posts = paginator.get_page(page_number)

    context = {'page_posts': page_posts, }

    return render(request, 'posts/follow.html', context)


def country_posts(request: HttpRequest, slug: str) -> HttpResponse:
    country = get_object_or_404(Country, slug=slug)
    posts = country.posts.all()
    paginator = Paginator(posts, posts_per_page)
    page_number = request.GET.get('page')
    page_posts = paginator.get_page(page_number)

    context: Dict[str, str] = {
        'country': country,
        'page_posts': page_posts,
    }
    templates = 'posts/country_posts.html'

    return render(request, templates, context)


def profile(request: HttpRequest, user_name: str) -> HttpResponse:
    user = get_object_or_404(User, username=user_name)
    posts = Post.objects.filter(author=user)

    paginator = Paginator(posts, posts_per_page)
    page_number = request.GET.get('page')
    page_posts = paginator.get_page(page_number)

    follow_list = Follow.objects.all()
    following = False
    if request.user.is_authenticated:
        following = follow_list.filter(user=request.user, author=user).exists()
    followers_count = follow_list.filter(author=user).count()
    following_count = follow_list.filter(user=user).count()

    context = {
        'page_posts': page_posts,
        'author': user,
        'posts': posts,
        'following': following,
        'followers_count': followers_count,
        'following_count': following_count,
    }

    templates = 'posts/profile.html'

    return render(request, templates, context)


def post_detail(request: HttpRequest, post_id: int) -> HttpResponse:
    post = get_object_or_404(Post, pk=post_id)
    comments = post.comments.all()

    form = CommentForm(request.POST or None)

    context = {
        'post': post,
        'comments': comments,
        'form': form,
    }

    templates = 'posts/post_detail.html'

    return render(request, templates, context)


@login_required(login_url='users:login')
def post_create(request: HttpRequest) -> HttpResponse:
    form = PostForm(request.POST or None,
                    files=request.FILES or None)
    if form.is_valid():
        new_post = form.save(commit=False)
        new_post.author = request.user
        new_post.save()

        return redirect('travel_posts:profile', request.user)

    return render(request, 'posts/create_post.html', {'form': form})


@login_required(login_url='users:login')
def post_edit(request: HttpRequest, post_id: int) -> HttpResponse:
    post = get_object_or_404(Post, id=post_id)

    if post.author != request.user:
        return redirect('travel_posts:main')

    form = PostForm(request.POST or None,
                    files=request.FILES or None,
                    instance=post)
    if form.is_valid():
        form.save()

        return redirect('travel_posts:post_detail', post_id)

    return render(
        request,
        'posts/update_post.html',
        {'form': form, 'post': post}
    )


@login_required(login_url='users:login')
def add_comment(request: HttpRequest, post_id: int) -> HttpResponse:
    post = get_object_or_404(Post, id=post_id)

    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('travel_posts:post_detail', post_id)


@login_required(login_url='users:login')
def profile_follow(request: HttpRequest, user_name: str) -> HttpResponse:
    author = get_object_or_404(User, username=user_name)

    already_follow = Follow.objects.filter(user=request.user, author=author)
    if request.user != author and not already_follow:
        Follow.objects.create(user=request.user, author=author)

    return redirect('travel_posts:profile', user_name)


@login_required(login_url='users:login')
def profile_unfollow(request: HttpRequest, user_name: str) -> HttpResponse:
    author = get_object_or_404(User, username=user_name)
    Follow.objects.filter(user=request.user, author=author).delete()

    return redirect('travel_posts:profile', user_name)


@login_required(login_url='users:login')
def post_like(request: HttpRequest, post_id: int) -> HttpResponse:
    post = get_object_or_404(Post, pk=post_id)

    already_like = Like.objects.filter(user=request.user, post=post)
    if not already_like:
        Like.objects.create(user=request.user, post=post)

    return HttpResponseRedirect(
        request.META.get('HTTP_REFERER'),
        reverse('travel_posts:post_detail', kwargs={'post_id': post_id})
    )


@login_required(login_url='users:login')
def post_dislike(request: HttpRequest, post_id: int) -> HttpResponse:
    post = get_object_or_404(Post, pk=post_id)
    Like.objects.filter(user=request.user, post=post).delete()

    return HttpResponseRedirect(
        request.META.get('HTTP_REFERER'),
        reverse('travel_posts:post_detail', kwargs={'post_id': post_id})
    )

templates/posts/country_posts.html
{% extends 'base.html' %}
{% block title %} Posts about {{ country.title }} {% endblock %}
{% block content %}
    <h1 class="title">Posts about {{ country.title }}</h1>
    <div class="cards-container">
    {% for post in page_posts %}
        {% include 'includes/post_card.html' %}
    {% endfor %}
    </div>
    {% include 'includes/paginator.html' %}
{% endblock %}

templates/posts/create_post.html
{% extends "base.html" %}
{% block title %}New post{% endblock %}
{% block content %}
{% load user_filters %}
<div>
    <h1 class="title">New post</h1>
    <div class="form-container">
        {% if form.errors %}
        {% for field in form %}
        {% for error in field.errors %}
        <div>
            {{ error|escape }}
        </div>
        {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
        <div>
            {{ error|escape }}
        </div>
        {% endfor %}
        {% endif %}

        <form method="post"
              enctype="multipart/form-data"
              {% if action_url %}
              action="{% url action_url %}"
              {% endif %}
        >
            {% csrf_token %}

            {% for field in form %}
            <fieldset class="form__input-container"
                    {% if field.field.required %}
                    aria-required="true"
                    {% else %}
                    aria-required="false"
                    {% endif %}
            >
                {% if field.field.widget.input_type != 'file' %}
                    <label for="{{ field.id_for_label }}">
                        {{ field.label }}
                        {% if field.field.required %}
                            <span>*</span>
                        {% endif %}
                    </label>
                    <div>
                        {{ field|addclass:'form__input' }}
                        {% if field.help_text %}
                        <small id="{{ field.id_for_label }}-help">
                            {{ field.help_text|safe }}
                        </small>
                        {% endif %}
                    </div>
                {% else %}
                    <label for="{{ field.id_for_label }}" class="image-label">
                        {{ field.label }}

                        {% if field.field.required %}
                            <span>*</span>
                        {% endif %}

                        {{ field|addclass:'form__input_file' }}
                        <div class="button__choose-file">Choose file</div>
                        {% if field.help_text %}
                        <small id="{{ field.id_for_label }}-help">
                            {{ field.help_text|safe }}
                        </small>
                        {% endif %}
                    </label>
                {% endif %}
            </fieldset>
            {% endfor %}
            <button type="submit" class="form__button">Add</button>
        </form>
    </div>
</div>
{% endblock %}

templates/posts/follow.html
{% extends 'base.html' %}
{% block title %}Travel Blog{% endblock %}
{% block content %}
<div>
    <h1 class="title">The favorites posts</h1>
    {% include 'includes/switcher.html' %}
    <div class="cards-container">
    {% for post in page_posts %}
        {% include 'includes/post_card.html' %}
    {% endfor %}
    </div>
    {% include 'includes/paginator.html' %}
</div>
{% endblock %}

templates/posts/index.html
{% extends 'base.html' %}
{% block title %}Travel Blog{% endblock %}
{% block content %}
    <h1 class="title">The newest posts</h1>
    {% include 'includes/switcher.html' %}
    <div class="cards-container">
    {% for post in page_posts %}
        {% include 'includes/post_card.html' %}
    {% endfor %}
    </div>
    {% include 'includes/paginator.html' %}
{% endblock %}

templates/posts/post_detail.html
{% extends 'base.html' %}
{% block title %}Post {{ post.text|truncatechars:25 }}{% endblock %}
{% block content %}
    <h1 class="title">Post details</h1>
    {% include 'includes/post_card.html' %}
    {% include 'includes/comments.html' %}
{% endblock %}

templates/posts/profile.html
{% extends 'base.html' %}
{% block title %}{{ author }} profile{% endblock %}
{% block content %}
<div>
    <h1 class="title">All {{ author }}'s posts</h1>
    <div class="profile-container">
        <p class="text">Posts {{ posts.count }}</p>
        <p class="text">Followers {{ followers_count }}</p>
        <p class="text">Following {{ following_count }}</p>
        {% if user != author %}
            {% if following %}
                <a class="link-button" href="{% url 'travel_posts:profile_unfollow' author.username %}">Unfollow</a>
            {% else %}
                <a class="link-button" href="{% url 'travel_posts:profile_follow' author.username %}">Follow</a>
            {% endif %}
        {% endif %}
    </div>

    <div class="cards-container">
        {% for post in page_posts %}
        {% include 'includes/post_card.html' %}
        {% endfor %}
        {% include 'includes/paginator.html' %}
    </div>
</div>
{% endblock %}

templates/posts/update_post.html
{% extends "base.html" %}
{% block title %}Edit post{% endblock %}
{% block content %}
{% load user_filters %}
<div>
    <h1 class="title">Edit post</h1>
    <div class="form-container">
        {% if form.errors %}
        {% for field in form %}
        {% for error in field.errors %}
        <div>
            {{ error|escape }}
        </div>
        {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
        <div>
            {{ error|escape }}
        </div>
        {% endfor %}
        {% endif %}

        <form method="post"
              enctype="multipart/form-data"
              {% if action_url %}
              action="{% url action_url %}"
              {% endif %}
        >
            {% csrf_token %}

            {% for field in form %}
            <fieldset class="form__input-container"
                    {% if field.field.required %}
                    aria-required="true"
                    {% else %}
                    aria-required="false"
                    {% endif %}
            >
                {% if field.field.widget.input_type != 'file' %}
                <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                    {% if field.field.required %}
                    <span>*</span>
                    {% endif %}
                </label>
                <div>
                    {{ field|addclass:'form__input' }}
                    {% if field.help_text %}
                    <small id="{{ field.id_for_label }}-help">
                        {{ field.help_text|safe }}
                    </small>
                    {% endif %}
                </div>
                {% else %}
                    <label for="{{ field.id_for_label }}" class="image-label">
                        {{ field.label }}

                        {% if field.field.required %}
                            <span>*</span>
                        {% endif %}

                        {{ field|addclass:'form__input_file' }}
                        <div class="button__choose-file">Choose file</div>
                        {% if field.help_text %}
                        <small id="{{ field.id_for_label }}-help">
                            {{ field.help_text|safe }}
                        </small>
                        {% endif %}
                    </label>
                {% endif %}
            </fieldset>
            {% endfor %}
            <button type="submit" class="form__button">Save</button>
        </form>
    </div>
</div>
{% endblock %}