posts/urls.py
from django.urls import path
from . import views


app_name = 'travel_posts'

urlpatterns = [
    path('', views.index, name='main'),
    path('follow/', views.follow_index, name='follow_index'),
    path('country/<slug:slug>/', views.country_posts, name='country_posts'),
    path(
        'profile/<str:user_name>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:user_name>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
    path('profile/<str:user_name>/', views.profile, name='profile'),
    path('create/', views.post_create, name='post_create'),
    path('post/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('post/<int:post_id>/comment/', views.add_comment, name='add_comment'),
    path('post/<int:post_id>/like/', views.post_like, name='post_like'),
    path('post/<int:post_id>/dislike/', views.post_dislike, name='post_dislike'),
    path('post/<int:post_id>/', views.post_detail, name='post_detail'),
]

travel_blog/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='travel_posts')),
]

handler404 = 'core.views.page_not_found' # noqa
handler500 = 'core.views.server_error'  # noqa
handler403 = 'core.views.permission_denied' # noqa

urlpatterns += static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)
urlpatterns += static(
    settings.STATIC_URL, document_root=settings.STATIC_ROOT
)

users/urls.py
from django.contrib.auth.views import (
    LogoutView,
    LoginView,
    PasswordChangeView,
    PasswordChangeDoneView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)
from django.urls import path
from . import views


app_name = 'users'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout',
    ),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login',
    ),
    path(
        'password_change/done/',
        PasswordChangeDoneView.as_view(
            template_name='users/password_change_done.html'
        ),
        name='password_change_done',
    ),
    path(
        'password_change/',
        PasswordChangeView.as_view(
            template_name='users/password_change_form.html'
        ),
        name='password_change',
    ),
    path(
        'password_reset/done/',
        PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html'
        ),
        name='password_reset_done',
    ),
    path(
        'password_reset/',
        PasswordResetView.as_view(
            template_name='users/password_reset_form.html'
        ),
        name='password_reset',
    ),
    path(
        'reset/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html'
        ),
        name='password_reset_confirm',
    ),
    path(
        'reset/done/',
        PasswordResetCompleteView.as_view(
            template_name='users/password_reset_complete.html'
        ),
        name='password_reset_complete',
    ),
]

templates/includes/comments.html
<!-- comments adding form -->
{% load user_filters %}
<div class="comments-container">
    {% if user.is_authenticated %}
    <div class="form-container">
        <form
                class="form"
                method="post"
                action="{% url 'travel_posts:add_comment' post.pk %}"
        >
            {% csrf_token %}

            {% for field in form %}
            <fieldset class="form__input-container"
                      {% if field.field.required %}
                      aria-required="true"
                      {% else %}
                      aria-required="false"
                      {% endif %}
            >
                <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                    {% if field.field.required %}
                    <span>*</span>
                    {% endif %}
                </label>

                {{ field|addclass:'form__input' }}
                {% if field.help_text %}
                <small id="{{ field.id_for_label }}-help">
                    {{ field.help_text|safe }}
                </small>
                {% endif %}

            </fieldset>
            {% endfor %}
            <button type="submit" class="form__button">Send</button>
        </form>
    </div>
    {% endif %}

    <!-- comments list -->
    <h5 class="comment__title">Comments:</h5>
    {% if comments.count > 0 %}
    {% for item in comments %}
    <div class="comment">
        <a class="comment__author" href="{% url 'travel_posts:profile' item.author.username %}"
           name="comment_{{ item.id }}">
            {{ item.author.username }}:
        </a>
        <p class="comment__text">{{ item.text | linebreaksbr }}</p>
    </div>
    {% endfor %}
    {% else %}
        <p class="comment__text">There are no comments, yet...</p>
    {% endif %}
</div>

templates/includes/footer.html
<footer class="footer">
    {% include 'includes/nav_footer.html' %}
    <p class="footer__text">© {{ year }} Copyright Travel Blog</p>
</footer>

templates/includes/header.html
<header class="header">

    <div class="logo">
        <a class="logo__link" href="{% url 'travel_posts:main' %}">Travel Blog</a>
    </div>

    <div class="menu__container">

        <div class="user">
            {% if user.is_authenticated %}
                <a class="user__link" href="{% url 'travel_posts:profile' user.username %}">{{ user }}</a>
            {% else %}
                <a class="user__link" href="{% url 'users:login' %}">login</a>
                <a class="user__link" href="{% url 'users:signup' %}">signup</a>
            {% endif %}
        </div>

        {% include 'includes/nav_header.html' %}

    </div>
</header>

templates/includes/menu.html
{% if user.is_authenticated %}
<div class="overlay"></div>
<nav class="sidebar-menu">

    <ul class="sidebar-menu__items">
        <li class="sidebar-menu__item">
            <a class="sidebar-menu__link" href="{% url 'travel_posts:post_create' %}">Create post</a>
        </li>
        <li class="sidebar-menu__item">
            <a class="sidebar-menu__link" href="{% url 'users:password_change' %}">change password</a>
        </li>
        <li class="sidebar-menu__item">
            <a class="sidebar-menu__link" href="{% url 'users:logout' %}">logout</a>
        </li>
    </ul>

</nav>
{% endif %}

templates/includes/nav_footer.html
<nav class="menu">
    {% with request.resolver_match.view_name as view_name %}
    <ul class="menu__items">
    </ul>
    {% endwith %}
</nav>

templates/includes/nav_header.html
{% if user.is_authenticated %}
<nav class="menu">

    <ul class="menu__items">
        <li class="menu__item">
            <a class="menu__link" href="{% url 'travel_posts:post_create' %}">Create post</a>
        </li>
        <li class="menu__item">
            <a class="menu__link" href="{% url 'users:password_change' %}">change password</a>
        </li>
        <li class="menu__item">
            <a class="menu__link" href="{% url 'users:logout' %}">logout</a>
        </li>
    </ul>
    <input id="menu__toggle" type="checkbox" />
    <div class="menu__button"></div>

</nav>
{% endif %}

templates/includes/paginator.html
{% if page_posts.has_other_pages %}
<nav class="paginator">
  <ul class="paginator__items">
    {% if page_posts.has_previous %}
      <li class="paginator__item paginator__item_start-end">
        <a class="paginator__link" href="?page=1">❘◀</a>
      </li>
      <li class="paginator__item paginator__item_step">
        <a class="paginator__link" href="?page={{ page_posts.previous_page_number }}">◀</a>
      </li>
    {% endif %}
    {% for i in page_posts.paginator.page_range %}
        {% if page_posts.number == i %}
          <li class="paginator__item paginator__item_checked">{{ i }}</li>
        {% else %}
          <li class="paginator__item">
            <a class="paginator__link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
    {% endfor %}
    {% if page_posts.has_next %}
      <li class="paginator__item paginator__item_step">
        <a class="paginator__link" href="?page={{ page_posts.next_page_number }}">▶</a>
      </li>
      <li class="paginator__item paginator__item_start-end">
        <a class="paginator__link" href="?page={{ page_posts.paginator.num_pages }}">▶❘</a>
      </li>
    {% endif %}
  </ul>
</nav>
{% endif %}

templates/includes/post_card.html
{% with request.resolver_match.view_name as view_name %}
<article class="post-card {% if view_name == 'travel_posts:post_detail' %}post-card_detail{% endif %}">
    {% load static %}

    <ul class="post-card__info">
        <li class="post-card__info-item">
            Author: <a href="{% url 'travel_posts:profile' post.author.username %}">{{ post.author }}</a>
        </li>
        <li class="post-card__info-item">
            Date: {{ post.pub_date|date:"d.m.Y" }}
        </li>
    </ul>

    {% if view_name != 'travel_posts:post_detail' and post.pk %}
    <a href="{% url 'travel_posts:post_detail' post.pk %}" class="post-card__img-link">
        <p class="post-card__text">{{ post.text }}</p>
    </a>
    {% else %}
        <p class="post-card__text post-card__text_detail">{{ post.text }}</p>
    {% endif %}

    {% if view_name != 'travel_posts:country_posts' and post.country %}
    <a href="{% url 'travel_posts:country_posts' post.country.slug %}" class="post-card__link">See all {{ post.country.title }} posts</a>
    {% endif %}

    {% if view_name != 'travel_posts:post_detail' and post.pk %}
        <a href="{% url 'travel_posts:post_detail' post.pk %}" class="post-card__img-link">
        {% load thumbnail %}
        {% thumbnail post.image "1440x960" upscale=False as im %}
            <img class="post-card__image" src="{{ im.url }}">
        {% endthumbnail %}
        </a>
    {% else %}
        {% load thumbnail %}
        {% thumbnail post.image "1440x960" upscale=False as im %}
            <img class="post-card__image post-card__image_detail" src="{{ im.url }}">
        {% endthumbnail %}
    {% endif %}

    <div class="post-card__handlers-container {% if view_name == 'travel_posts:post_detail' %}post-card__handlers-container_detail{% endif %}">
        {% if user.is_authenticated and post.already_like %}
            <a href="{% url 'travel_posts:post_dislike' post.pk %}" class="post-card__img-link">
                <img src="{% static 'img/heart_fill.png' %}" style="display: inline-block; width: 40px; height: 40px" alt="Dislike">
                <p class="post-card__counter post-card__counter_like">{{ post.likes.count }}</p>
            </a>
        {% else %}
            <a href="{% url 'travel_posts:post_like' post.pk %}" class="post-card__img-link">
                <img src="{% static 'img/heart_empty.png' %}" alt="Like" class="post-card__icon">
                <p class="post-card__counter post-card__counter_like">{{ post.likes.count }}</p>
            </a>
        {% endif %}

        <a href="{% url 'travel_posts:post_detail' post.pk %}" class="post-card__img-link">
        {% if post.comments_count > 0 %}
            <img src="{% static 'img/comments_fill.png' %}" alt="Post has a comments" class="post-card__icon">
        {% else %}
            <img src="{% static 'img/comments_empty.png' %}" alt="Post doesn't have a comments" class="post-card__icon">
        {% endif %}
            <p class="post-card__counter post-card__counter_comment">{{ post.comments_count }}</p>
        </a>

        {% if user.is_authenticated and user == post.author %}
            <a href="{% url 'travel_posts:post_edit' post.pk %}" class="post-card__img-link">
                <img src="{% static 'img/edit.png' %}" alt="Edit" class="post-card__icon">
            </a>
        {% endif %}

        {% if view_name != 'travel_posts:post_detail' and post.pk %}
            <a href="{% url 'travel_posts:post_detail' post.pk %}" class="post-card__img-link">
                <img src="{% static 'img/details.png' %}" alt="Post details" class="post-card__icon">
            </a>
        {% endif %}
    </div>


</article>
{% endwith %}

templates/includes/switcher.html
{% if user.is_authenticated %}
{% with request.resolver_match.view_name as view_name %}
    <ul class="switcher__items">
      <li class="switcher__item">
          <a
                  class="switcher__link {% if view_name == 'travel_posts:main' %}switcher__link_active{% endif %}"
                  href="{% url 'travel_posts:main' %}"
          >
            All
          </a>
      </li>
      <li class="switcher__item">
          <a
                  class="switcher__link {% if view_name == 'travel_posts:follow_index' %}switcher__link_active{% endif %}"
                  href="{% url 'travel_posts:follow_index' %}"
          >
            Favorites
          </a>
      </li>
    </ul>
{% endwith %}
{% endif %}