posts/urls.py
from django.urls import path
from . import views


app_name = 'travel_posts'

urlpatterns = [
    path('', views.index, name='main'),
    path('follow/', views.follow_index, name='follow_index'),
    path('country/<slug:slug>/', views.country_posts, name='country_posts'),
    path(
        'profile/<str:user_name>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:user_name>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
    path('profile/<str:user_name>/', views.profile, name='profile'),
    path('create/', views.post_create, name='post_create'),
    path('post/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('post/<int:post_id>/comment/', views.add_comment, name='add_comment'),
    path('post/<int:post_id>/like/', views.post_like, name='post_like'),
    path('post/<int:post_id>/dislike/', views.post_dislike, name='post_dislike'),
    path('post/<int:post_id>/', views.post_detail, name='post_detail'),
]

travel_blog/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='travel_posts')),
]

handler404 = 'core.views.page_not_found' # noqa
handler500 = 'core.views.server_error'  # noqa
handler403 = 'core.views.permission_denied' # noqa

urlpatterns += static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)
urlpatterns += static(
    settings.STATIC_URL, document_root=settings.STATIC_ROOT
)

users/urls.py
from django.contrib.auth.views import (
    LogoutView,
    LoginView,
    PasswordChangeView,
    PasswordChangeDoneView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)
from django.urls import path
from . import views


app_name = 'users'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout',
    ),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login',
    ),
    path(
        'password_change/done/',
        PasswordChangeDoneView.as_view(
            template_name='users/password_change_done.html'
        ),
        name='password_change_done',
    ),
    path(
        'password_change/',
        PasswordChangeView.as_view(
            template_name='users/password_change_form.html'
        ),
        name='password_change',
    ),
    path(
        'password_reset/done/',
        PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html'
        ),
        name='password_reset_done',
    ),
    path(
        'password_reset/',
        PasswordResetView.as_view(
            template_name='users/password_reset_form.html'
        ),
        name='password_reset',
    ),
    path(
        'reset/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html'
        ),
        name='password_reset_confirm',
    ),
    path(
        'reset/done/',
        PasswordResetCompleteView.as_view(
            template_name='users/password_reset_complete.html'
        ),
        name='password_reset_complete',
    ),
]

users/models.py
from django.db import models

# Create your models here.

users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model


User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')

users/views.py
from django.views.generic import CreateView
from django.urls import reverse_lazy
from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('travel_posts:main')
    template_name = 'users/signup.html'

templates/users/logged_out.html
{% extends 'base.html' %}
{% block title %}You are logged out!{% endblock %}
{% block content %}
<h1 class="title">Exit</h1>
<div class="form-container">
    <p class="text">You are logged out. See you soon!</p>
</div>
{% endblock %}

templates/users/login.html
{% extends "base.html" %}
{% block title %}Login{% endblock %}
{% block content %}
{% load user_filters %}

    <h1 class="title">Login</h1>
    <div class="form-container">
        {% if form.errors %}
        {% for field in form %}
        {% for error in field.errors %}
        <div>
            {{ error|escape }}
        </div>
        {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
        <div>
            {{ error|escape }}
        </div>
        {% endfor %}
        {% endif %}

        <form method="post"
              {% if action_url %}
              action="{% url action_url %}"
              {% endif %}
        >
            {% csrf_token %}

            {% for field in form %}
            <fieldset class="form__input-container"
                      {% if field.field.required %}
                      aria-required="true"
                      {% else %}
                      aria-required="false"
                      {% endif %}
            >
                <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                    {% if field.field.required %}
                    <span>*</span>
                    {% endif %}
                </label>
                <div>
                    {{ field|addclass:'form__input' }}
                    {% if field.help_text %}
                    <small id="{{ field.id_for_label }}-help">
                        {{ field.help_text|safe }}
                    </small>
                    {% endif %}
                </div>
            </fieldset>
            {% endfor %}

            <a class="link" href="{% url 'users:password_reset' %}">Forgot password?</a>
            <button type="submit" class="form__button">Login</button>
        </form>
    </div>

{% endblock %}

templates/users/password_change_done.html
{% extends 'base.html' %}
{% block title %}Password changed{% endblock %}
{% block content %}
<div>
    <h1 class="title">Password changed</h1>
    <div class="form-container">
        <p class="text">Now you can log in with a new password</p>
        <a class="link" href="{% url 'users:login' %}">Log in</a>
    </div>
</div>
{% endblock %}

templates/users/password_change_form.html
{% extends "base.html" %}
{% block title %}Change password{% endblock %}
{% block content %}
{% load user_filters %}

    <h1 class="title">Change password</h1>
    <div class="form-container">
        {% if form.errors %}
        {% for field in form %}
        {% for error in field.errors %}
        <div>
            {{ error|escape }}
        </div>
        {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
        <div>
            {{ error|escape }}
        </div>
        {% endfor %}
        {% endif %}

        <form method="post"
              {% if action_url %}
              action="{% url action_url %}"
              {% endif %}
        >
            {% csrf_token %}

            {% for field in form %}
            <fieldset class="form__input-container"
                    {% if field.field.required %}
                    aria-required="true"
                    {% else %}
                    aria-required="false"
                    {% endif %}
            >
                <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                    {% if field.field.required %}
                    <span>*</span>
                    {% endif %}
                </label>
                <div>
                    {{ field|addclass:'form__input' }}
                    {% if field.help_text %}
                    <small id="{{ field.id_for_label }}-help">
                        {{ field.help_text|safe }}
                    </small>
                    {% endif %}
                </div>
            </fieldset>
            {% endfor %}
            <button type="submit" class="form__button">Change</button>
        </form>
    </div>

{% endblock %}

templates/users/password_reset_complete.html
{% extends 'base.html' %}
{% block title %}Password changed{% endblock %}
{% block content %}

    <h1 class="title">Password changed</h1>
    <div class="form-container">
        <p class="text">Now you can log in with a new password!</p>
        <a class="link" href="{% url 'users:login' %}">Log in</a>
    </div>

{% endblock %}

templates/users/password_reset_confirm.html
{% extends "base.html" %}
{% block title %}Reset your password{% endblock %}
{% block content %}
{% load user_filters %}

    <h1 class="title">Reset your password</h1>
    {% if validlink %}
    <div class="form-container">
        {% if form.errors %}
        {% for field in form %}
        {% for error in field.errors %}
        <div>
            {{ error|escape }}
        </div>
        {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
        <div>
            {{ error|escape }}
        </div>
        {% endfor %}
        {% endif %}
        <form method="post"
              {% if action_url %}
              action="{% url action_url %}"
              {% endif %}
        >
            {% csrf_token %}
            {% for field in form %}
            <fieldset class="form__input-container"
                    {% if field.field.required %}
                    aria-required="true"
                    {% else %}
                    aria-required="false"
                    {% endif %}
            >
                <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                    {% if field.field.required %}
                    <span>*</span>
                    {% endif %}
                </label>
                <div>
                    {{ field|addclass:'form__input' }}
                    {% if field.help_text %}
                    <small id="{{ field.id_for_label }}-help">
                        {{ field.help_text|safe }}
                    </small>
                    {% endif %}
                </div>
            </fieldset>
            {% endfor %}
            <button type="submit" class="form__button">Save new password</button>
        </form>
    </div>
    {% else %}
    <div class="form-container">
        <p class="text_red">Error</p>
        <p class="text">The password reset link has is invalid or expired.</p>
    </div>
    {% endif %}

{% endblock %}

templates/users/password_reset_done.html
{% extends 'base.html' %}
{% block title %}Reset your password{% endblock %}
{% block content %}
<div>
    <h1 class="title">Reset your password</h1>
    <p class="text">Check your email for a link to reset your password. If it doesn’t appear within a few minutes, check your spam folder.</p>
</div>
{% endblock %}

templates/users/password_reset_form.html
{% extends "base.html" %}
{% block title %}Reset your password{% endblock %}
{% block content %}
{% load user_filters %}

    <h1 class="title">Reset your password</h1>
    <div class="form-container">
        {% if form.errors %}
        {% for field in form %}
        {% for error in field.errors %}
        <div>
            {{ error|escape }}
        </div>
        {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
        <div>
            {{ error|escape }}
        </div>
        {% endfor %}
        {% endif %}
        <form method="post"
              {% if action_url %}
              action="{% url action_url %}"
              {% endif %}
        >
            {% csrf_token %}
            {% for field in form %}
            <fieldset class="form__input-container"
                    {% if field.field.required %}
                    aria-required="true"
                    {% else %}
                    aria-required="false"
                    {% endif %}
            >
                <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                    {% if field.field.required %}
                    <span>*</span>
                    {% endif %}
                </label>
                <div>
                    {{ field|addclass:'form__input' }}
                    {% if field.help_text %}
                    <small id="{{ field.id_for_label }}-help">
                        {{ field.help_text|safe }}
                    </small>
                    {% endif %}
                </div>
            </fieldset>
            {% endfor %}

            <button class="form__button" type="submit">Send password reset email</button>

        </form>
    </div>
{% endblock %}

templates/users/signup.html
<!-- templates/users/signup.html -->
{% extends "base.html" %}
{% block title %}Sign up{% endblock %}
{% block content %}
{% load user_filters %}
<div>
    <h1 class="title">Sign up for Travel Blog</h1>
    <div class="form-container">
        {% if form.errors %}
        {% for field in form %}
        {% for error in field.errors %}
        <div>
            {{ error|escape }}
        </div>
        {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
        <div>
            {{ error|escape }}
        </div>
        {% endfor %}
        {% endif %}

        <form method="post" action="{% url 'users:signup' %}">
            {% csrf_token %}
            {% for field in form %}
            <fieldset class="form__input-container">
                <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                    {% if field.field.required %}
                    <span class="required text-danger">*</span>
                    {% endif %}
                </label>
                {{ field|addclass:'form__input' }}
                {% if field.help_text %}
                <small id="{{ field.id_for_label }}-help">
                    {{ field.help_text|safe }}
                </small>
                {% endif %}
            </fieldset>
            {% endfor %}
            <button class="form__button" type="submit">Sign up</button>
        </form>
    </div>
</div>
{% endblock %}